name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Configure Version
      run: |
        echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:latest -t ${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:${{ env.VERSION }} .
    - name: Publish Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare
