name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Configure Version
      run: |
        echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        version: latest
    - name: Build Regular Image
      run: |
        docker buildx build --push \
        -t ${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:latest \
        -t ${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:${{ env.VERSION }} \
        --platform linux/amd64,linux/arm/v7,linux/arm64 -f ./Dockerfile.caddy .
    - name: Build Alpine Image
      run: |
        docker buildx build --push \
        -t ${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:latest-alpine \
        -t ${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:${{ env.VERSION }}-alpine \
        --platform linux/amd64,linux/arm/v7,linux/arm64 -f ./Dockerfile.caddy-alpine .
